### PR TITLE
Update to Selenium 4.8.0

### PR DESCRIPTION
**Pull request by rbourga**
Update of libs to Selenium 4.8.0.

### CODE REVIEW

**Comment by rbourga** [comment]
Hi Andrey,
It looks like version 4.8.0 has not made it to maven even if the build is
successful.
This is causing my PR request in jmeter-plugins repo to fail:

Can you please have a look?
Thanks.

1015	DEBUG	"GET
/maven2/kg/apc/jmeter-plugins-webdriver/4.8.0/jmeter-plugins-webdriver-4.8.0.jar
HTTP/1.1" 404 554
1019Traceback (most recent call last):
1020  File "downloads.py", line 144, in <module>
1021    plugin.get('installerClass'))
1022  File "downloads.py", line 39, in pack_version
1023    jar_path = download_into_dir(tmp_dir, ver_obj['downloadUrl'],
os.path.join("lib", "ext"))
1024  File "downloads.py", line 68, in download_into_dir
1025    assert resp.status_code == 200
1026AssertionError
1027The command "python -m virtualenv --system-site-packages ./venv &&
source venv/bin/activate && python -m pip install jsonschema &&
./prepare-upload.sh" failed and exited with 1 during .


Le mar. 14 févr. 2023 à 16:40, Andrey Pokhilko ***@***.***> a
écrit :

**Comment by undera** [comment]
I have published it to maven, should appear soon

**Comment by rbourga** [comment]
Thanks Andrey¿I can see it now.
Could you trigger the "PR #567 Update of WebDriver plugin to 4.8.0" build
again as I don't have authority for that.
It should now pass!
Thanks again.
Regards
Robert.

Le mer. 15 févr. 2023 à 21:46, Andrey Pokhilko ***@***.***> a
écrit :

**Comment by shubh1212** [comment]
I dont see the latest version of jmeter-plugins-webdriver 4.8.0 in mvnrepository yet. I need jars , to enable new chrome support. Can someone share the link to get jars

**Comment by rbourga** [comment]
Hi Subbh,
New 4.8.0 webdriver package should be integrated in the Plugin Manager soon.
However, you can predownload the jar at Central Repository:
kg/apc/jmeter-plugins-webdriver/4.8.0 (maven.org)
<https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-webdriver/4.8.0/>.
Note that you would need Selenium 4.8.0 jars to go with it (which the
Plugin Manager does for you)...

Le jeu. 16 févr. 2023 à 14:01, shubh1212 ***@***.***> a
écrit :

**Comment by undera** [comment]
It hits the same problem as described in https://github.com/undera/jmeter-plugins/pull/568 

We need to find a solution to it, to unblock all PRs

**Pull request merged**
