### PR TITLE
Project update to Selenium 4.5 and JDK 17

### PR DESCRIPTION
**Pull request by rbourga**
Changes across the board to comply with Selenium 4.4 and JDK 17.
In particular:
- Inclusion of previous pull-request changes that were pending because of test failures;
- Removal of deprecated phantomjs driver;
- Addition of "path field" for Geckodriver in Firefox GUI and removal of deprecated "Legacy" feature;
- Addition of "path to Edge" in IE GUI (so IE 11 now runs in Edge as per Microsoft recommendations);
- Dependencies updated accordingly in pom.xml;

### CODE REVIEW

**Comment by rbourga** [comment]
Before building the jar, you will have to edit FirefoxDriverConfigTest.java and update the path to the GeckoDriver on the build machine (see line 81) as the test was originally designed to work like this.

**Comment by undera** [comment]
You will need to alter the CI config to download the required GeckoDriver, for tests to work.

**Comment by rbourga** [comment]
I am a bit confused! Where is the CI config file located? And then how do I reference the GeckoDriver in the test?
Thanks!

**Comment by undera** [comment]
The TravisCI pipeline is configured in this file: https://github.com/undera/jmeter-plugins-webdriver/blob/master/.travis.yml

It is common to make `install` section a multi-step process and download/setup required stuff there.

I would configure the default location of any binary to be in path. I would do it on the level of plugin default. For example, for plugin to have a default of binary as `geckodriver`, assuming it is in the search path of the OS.
In the CI pipeline, I would download the required binary and put it into directory `/usr/local/bin` or whatever is configured in the CI environment.

**Comment by undera** [comment]
For example, look at multi-step install in https://github.com/undera/jmeter-plugins/blob/master/.travis.yml

**Comment by undera** [comment]
Committing the binary into repository is a bad idea, it is insecure and platform-dependent. Instead, you should make a script that would download the driver

**Comment by rbourga** [comment]
Have added Geckodriver to tests/resources folder and pointing the test to that file.
Builds nicely at my end!

**Comment by undera** [comment]
For example: http://www.columbia.edu/~njn2118/journal/2016/10/28.html
A bit old example, but gives you the idea

**Comment by rbourga** [comment]
Integration of this version in the plugin manager (jmeter-plugins) will require a complete rewrite of the list of libs in jpgc-plugins.json.

**Comment by undera** [comment]
You should prepare a PR with the change of plugin descriptor then, reflecting your knowledge of libs change. We'll merge it once the work on this upgrade is complete.

**Comment by rbourga** [comment]
Also please note that the Firefox tests do not require the Geckodriver anymore. It uses same logic similar to the tests for Chrome an Internet Explorer (which do not require their respective drivers for the tests to pass).
With this in mind, it is not required to edit .travis.yml file anymore to have setup steps to download the geckodriver.
Thanks.

**Comment by undera** [comment]
Please review the CI failures. Those might indicate the you have broken something in the old behavior of the plugin.

**Comment by undera** [comment]
Alright, now CI is green. I will merge it and will release the new version

**Comment by undera** [comment]
Massive work, thank you very much @rbourga !

**Pull request merged**
